### ISSUE TITLE
RestResponse on Bad Request

### ISSUE THREAD

**Issue by PenaPP** [FubarDevelopment/restsharp.portable#33]
Maybe I am doing something wrong, but everytime server returns Bad Reqest (400), Conflict (409), etc. HttpRequestException occurs... I thought it should be processed inside RestSharp.Portable and returned as StatusCode in RestResponse.
I am using version 3.0.0 alpha 4

**Comment by fubar-coder** [comment]
Yes, this is a difference between RestSharp.Portable and the original [RestSharp](https://github.com/restsharp/RestSharp), because it seemed much more convenient, because I (very) often saw the test for status codes and throwing custom exceptions, which is IMHO unnecessary boilerplate code. However, you can set the property ```IgnoreResponseStatusCode``` to ```true``` to get the behavior you expect.

**Comment by PenaPP** [comment]
Good to know - our project moved to RestSharp.Portable recently, so we already have the "unnecessary boilerplate code" there ;) Thank you for fast answer and explanation.
