### ISSUE TITLE
Catch exception from HttpClient SendAsync

### ISSUE THREAD

**Issue by spaswin** [FubarDevelopment/restsharp.portable#39]
Hi,

I am unable to catch the actual exception if i used httpclient sendasync method. how it should be catched the exception?

Thanks
Aswin S P

**Comment by fubar-coder** [comment]
I'm not sure what you mean. Due to the nature of async/await (or TPL in the background), You'll always(?) get an ```AggregateException```. Please read [this question on StackOverflow](http://stackoverflow.com/questions/7896376/tpl-exception-handling) and [this article on MSDN](https://msdn.microsoft.com/library/Dd997415.aspx) about the TPL and exception handling.

Maybe I misunderstood you. If this is the case, then please don't hesitate and attach an example to this issue and I'll reopen it.
