### ISSUE TITLE
Problem with using in iOS Unified project

### ISSUE THREAD

**Issue by gabornemeth** [FubarDevelopment/restsharp.portable#44]
After added Nuget package to an iOS Unified class library, I receive:
```Error CS0012: The type `System.Object' is defined in an assembly that is not referenced. Consider adding a reference to assembly `System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' (CS0012)```
This occurs when for example defining a class inherited from JsonConverter.
In iOS Classic class library it works fine.

**Comment by fubar-coder** [comment]
It's a known problem. Updating Newtonsoft.Json to version 7.0.1 worked for me. Everything should work as expected. Otherwise, you can try the latest beta of RestSharp.Portable.WebRequest which references Newtonsoft.Json 7.0.1 by default.

Alternatively, you may try the solution found [here in the Xamarin forums](https://forums.xamarin.com/discussion/24190/missing-system-objectmodel-system-runtime-assemblies).
