### ISSUE TITLE
Service hangs when app was built with the mtouch parameter --tls-provider=appletls

### ISSUE THREAD

**Issue by Aktar** [FubarDevelopment/restsharp.portable#60]
Hi there,
[Xamarin.iOS 9.8](https://developer.xamarin.com/releases/ios/xamarin.ios_9/xamarin.ios_9.8/) introduced Apple TLS support for ios apps. However, if I enable this option I will have some random hangs on service calls.
I noticed the timeout I defined (5 seconds) for the client is not considered, and the call will hang for about 50 seconds.

I'm trying to use native APIs as often as possible, what why I'm wondering if you plan on adding Apple TLS support to RestSharp ?

thanks

**Comment by fubar-coder** [comment]
I use Xamarins HttpClient implementation, so this problem might be caused by Xamarin. However, you should be able to use either the WebRequest version of RestSharp.Portable or the native [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient). You may find some useful hints about its usage in issue #34.
