### ISSUE TITLE
Response.Content property

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#63]
Sorry to be a pain, Restsharp has a Content property but this lib doesnt, I can only see RawBytes.  Is it possible to retrieve a string representation of the body anyway?  I see you have some HttpContent extensions marked as internal in the codebase, would a extension to get this out be an idea for a PR?

**Comment by fubar-coder** [comment]
I'd like to get a `Content` property PR. The main problem is, that you have to get the correct character set for the response. This might or might not be available as HTTP header. Even when it's available, it might differ when you receive HTML(SGML) or XML content. It's difficult to get right and the conversion should only be done, when the content property gets accessed, to avoid unnecessary memory allocations.

My "solution" was to leverage all those problems to the user of the library, because the user knows best, how to handle the raw data.

**Comment by Yantrio** [comment]
https://github.com/restsharp/RestSharp/blob/master/RestSharp/RestResponse.cs#L74 Looks like the original restsharp was quite lazy in this.

**Comment by jchannon** [comment]
https://github.com/restsharp/RestSharp/blob/80c1e49f322eebd19519fd79b7dd4c497c469a6e/RestSharp/Extensions/MiscExtensions.cs#L91

**Comment by jchannon** [comment]
Seem to do some detection? Could it be "borrowed" ? 😄

**Comment by fubar-coder** [comment]
Yes, I guess it could :wink: . Do you want to try making a PR, or should I do this? However, I cannot do this now, as I'm quite busy this week.

**Comment by jchannon** [comment]
I can do it in an hour or so.

Do you have a release schedule and if so when would it make it into a
release?

Thanks

**Comment by fubar-coder** [comment]
I guess, that I'm able to release the new version by tomorrow or the day after tomorrow.

**Comment by jchannon** [comment]
@fubar-coder I added a PR #65

**Comment by fubar-coder** [comment]
Thank you

**Comment by fubar-coder** [comment]
Can you test this new release? Please close this issue when everything works as expected.

**Comment by jchannon** [comment]
Will do! Thanks
