### ISSUE TITLE
Restsharp portable parallel requests are sent successively by one instance of RestClient

### ISSUE THREAD

**Issue by zevsst** [FubarDevelopment/restsharp.portable#66]
Hello, Mark.

I have some issue with parallelism of my rest calls. Please, have a look at:
[stackoverflow](http://stackoverflow.com/questions/37164129/restsharp-portable-parallel-requests-are-sent-successively-by-one-instance-of-re)

Thanks.

**Comment by fubar-coder** [comment]
HttpClient didn't support parallel requests, which is the only reason AsyncLock exists. Maybe they've changed its implementation, but I haven't tested it yet.

I personally don't like the AsyncLock stuff, and I'll change the code soon to allow parallel requests when using HttpWebRequest instead of HttpClient.

A possible solution around this limitation would be to use pooling for `IRestClient` instances.
