### ISSUE TITLE
Help: Support of SSL and TSL

### ISSUE THREAD

**Issue by iducool** [FubarDevelopment/restsharp.portable#87]
Hi,
I am using RestSharp portable version 2.4.3. Now I am planning to use "HTTPS" (either SSL or TSL) in app before uploading it to store. After reading some blogs on internet I am really confused about it. I have few questions 

- Does RestSharp portable support SSL/TSL by default? or do I need to do anything extra for it? 
- I ready on internet that Mono is not supporting SSL fully yet. Is it true?
- At this moment Apple Transport security layer(ATS) is not affecting anything on HTTPClient. Any way to make ATS compliant?

I know that some of the questions are not related to library but I am almost done and stuck at a place and don't want to rework everything with other library. Kindly answer these question in detail.

**Comment by fubar-coder** [comment]
RestSharp.Portable supports SSL/TLS by default due to the support of the underlying HttpClientHandler - except maybe on mono platforms. However, you can work around this problem by creating your own `IHttpClientFactory` implementation by deriving from `RestSharp.Portable.HttpClient.Impl.DefaultHttpClientFactory` and overriding `DefaultHttpClientFactory.CreateMessageHandler`.

You can return a `NativeMessageHandler` (from the [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient) project - which should be available as NuGet package.

Now, your app uses the native `NSUrlSession`, which (maybe) solves your problems.
